print("rafif reinhart ")
print("rafif reinhart ")
print("rafif reinhart ")
print("rafif reinhart ")
print("rafif reinhart al aflah")
print("rafif reinhart al aflah")
print("rafif reinhart al aflah")
print("rafif reinhart al aflah")