print("Menu:")
print("1. Burger")
print("2. Fried Chicken")
print("3. Instant Noodle")
print("Mau yang mana? :") 
food_option = int(input())

print("Menu:")
print("1. Avocado Juice")
print("2. Thai Tea")
print("3. Milk Tea")
print("Enter your choice: ")
beverage_option = int(input())

print("Menu:")
print("1. Fried fries")
print("2. Kerupuk")
print("3. Doughnut")
print("Enter your choice: ")
additional_option = int(input())